apiVersion: v1
kind: Service
metadata:
  name: {{ include "tweet.db.fullname" . }}
  labels:
    {{- include "tweet.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  ports:
    - port: {{ .Values.dbService.port }}
      targetPort: {{ .Values.dbService.port }}
      protocol: TCP
  selector:
    {{- include "tweet.db.selectorLabels" . | nindent 4 }}