apiVersion: v1
kind: Service
metadata:
  name: {{ include "tweet.fullname" . }}
  labels:
    {{- include "tweet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.djangoService.type }}
  ports:
    - port: {{ .Values.djangoService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tweet.selectorLabels" . | nindent 4 }}