name: CI

on:
  pull_request:
  push:
    branches:
    tags:
      - "*.*.*"

env:
  IMAGE: ${{ vars.NCR_REGISTRY }}/follow-app

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.NCR_REGISTRY }}
          username: ${{ secrets.NCR_ACCESS_KEY }}
          password: ${{ secrets.NCR_SECRET_KEY }}

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

      - name: Get version
        if: startsWith(github.ref, 'refs/tags')
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: build-and-push
        if: startsWith(github.ref, 'refs/heads')
        uses: docker/build-push-action@v4
        with:
          context: follow_app
          tags: "${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
          push: true

      - name: build-and-push
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v4
        with:
          context: follow_app
          tags: "${{ env.IMAGE }}:${{ steps.version.outputs.VERSION }}"
          push: true
